myproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^oneplace/', include('oneplace.urls')),
    url(r'^nonprofit/', include('nonprofit.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

oneplace/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from oneplace import views
from . import views

app_name = 'oneplace'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^class/$', views.LessonView.as_view(), name='lesson'),
    url(r'^class/table/$', views.LessonTable, name='lesson_table'),
    #url(r'^class/table/$', views.LessonTableView.as_view(), name='lesson_table'),
    url(r'^class/add/$', views.LessonCreate.as_view(), name='lesson_add'),
    url(r'^class/update/(?P<pk>[0-9]+)/$', views.LessonUpdate.as_view(), name='lesson_update'),
    url(r'^class/delete/(?P<pk>[0-9]+)/$', views.LessonDelete.as_view(), name='lesson_delete'),
    url(r'^class/delete/(?P<pk>[0-9]+)/list/$', views.LessonDeleteList.as_view(), name='lesson_delete_list'),
    url(r'^class/calendar/$', views.calendar, name='calendar'),
    url(r'^student/$', views.StudentDisplayAll, name='student'),
    url(r'^student/add/$', views.StudentCreate.as_view(), name='student_add'),
    url(r'^student/update/(?P<pk>[0-9]+)/$', views.StudentUpdate.as_view(), name='student_update'),
    url(r'^student/delete/(?P<pk>[0-9]+)/$', views.StudentDelete.as_view(), name='student_delete'),
    url(r'^student/remove/(?P<studentpk>[0-9]+)/(?P<lessonpk>[0-9]+)$', views.StudentRemove, name='student_remove'),
    url(r'^instructor/$', views.InstructorDisplayAll, name='instructor'),
    url(r'^instructor/add/$', views.InstructorCreate.as_view(), name='instructor_add'),
    url(r'^instructor/delete/(?P<pk>[0-9]+)/$', views.InstructorDelete.as_view(), name='instructor_delete'),
    url(r'^instructor/update/(?P<pk>[0-9]+)/$', views.InstructorUpdate.as_view(), name='instructor_update'),
    url(r'^instructor/remove/(?P<instructorpk>[0-9]+)/(?P<lessonpk>[0-9]+)$', views.InstructorRemove, name='instructor_remove'),
    url(r'^student/enroll/$', views.StudentEnrollCreate.as_view(), name='student_enroll'),
    url(r'^instructor/assign/$', views.InstructorAssignCreate.as_view(), name='instructor_assign'),
    url(r'^class/enrollment/(?P<pk>[0-9]+)/$', views.ClassEnrollment, name='class_enrollment'),
    url(r'^register/$', views.UserFormView.as_view(), name='register'),
    url(r'^login/$', views.LoginFormView.as_view(), name='login'),
    url(r'^logout/$', views.logoutView, name='log_out'),
    url(r'^rest/api$', views.StudentList.as_view(), name='rest'),
    url(r'^chart/$', views.chart, name='chart'),
    url(r'^chart/charttotalstudent$', views.chart_total_student, name='chart_total_student'),
    url(r'^chart/chartclasspermonth$', views.chart_class_per_month, name='chart_class_per_month'),
    url(r'^chart/chartcapacity$', views.chart_capacity, name='chart_capacity'),
    url(r'^chart/chart_level$', views.chart_level, name='chart_level'),
    url(r'^test$', views.test, name='test'),
    
    ]

urlpatterns = format_suffix_patterns(urlpatterns)

#maybe use later
#url(r'^student/$', views.StudentView.as_view(), name='student'),
#url(r'^instructor/$', views.InstructorView.as_view(), name='instructor'),

oneplace/forms.py
from django.contrib.auth.models import User
from django import forms
from django.contrib.admin import widgets
from oneplace.models import Instructor, Student, Lesson, Lesson_level, Student_in_lesson, Instructor_in_lesson
from django.forms import ModelForm
from django.db import models


class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)
	
	class Meta:
		model = User
		fields = ['username', 'email', 'password']

class LoginForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)
	class Meta:
		model = User
		fields = ['username', 'password']



class StudentForm(forms.Form):
    start_time = forms.DateField(widget=forms.DateTimeInput)


class UploadFileForm(forms.Form):
    file = forms.FileField(label='Import CSV Data', required=False)

oneplace/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.views import generic
from django.views.generic import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from oneplace.models import Instructor, Student, Lesson, Lesson_level, Student_in_lesson, Instructor_in_lesson
from django.urls import reverse_lazy
from .forms import UserForm, LoginForm, StudentForm, UploadFileForm
from django.shortcuts import get_object_or_404
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from oneplace.serializers import StudentSerializer
import time, csv, datetime
from django.db.models import Count
from django.db.models.functions import TruncMonth
from django.core.files.uploadedfile import UploadedFile,  TemporaryUploadedFile
from io import TextIOWrapper


# Create your views here.
def index(request):

    return render(request, 'oneplace/index.html')

def logoutView(request):
    logout(request)
    return redirect('oneplace:index')

class LessonView(generic.ListView):
    template_name = 'oneplace/lesson.html'
    context_object_name ='lesson_all'
    def get_queryset(self):
        return Lesson.objects.all().order_by('start_time')

class LessonTableView(generic.ListView):
    template_name = 'oneplace/lessontable.html'
    context_object_name ='lesson_all'
    def get_queryset(self):
        return Lesson.objects.all().order_by('start_time')

def test(request):
    class_bulk_data = []
    
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        
        if form.is_valid():
          class_bulk_data  = handle_uploaded_file(request.FILES['file'].file, request)
          
          count_Save = 0
          for idx, row in enumerate(class_bulk_data):
              if idx > 0:
                  get_Level = Lesson_level.objects.get(level_name=class_bulk_data[idx][6])
                  new_Class_Entry = Lesson(class_name = class_bulk_data[idx][0], 
                                       class_description = class_bulk_data[idx][1], 
                                       class_capacity = class_bulk_data[idx][2],
                                       start_time = class_bulk_data[idx][3], 
                                       end_time = class_bulk_data[idx][4],
                                       room_location = class_bulk_data[idx][5],
                                       level = get_Level
                                       )
                  new_Class_Entry.save()
                  print (get_Level)
                  count_Save+=1
        print("You Saved:" + str(count_Save))
            
    else:
        form = UploadFileForm()
        

    return render(request, 'oneplace/test.html', {'form':form})

def handle_uploaded_file(f, request):
    class_bulk_data = []
    
    f=TextIOWrapper(request.FILES['file'].file, encoding=request.encoding)
    file_reader = csv.reader(f, delimiter=',', skipinitialspace=True)
    
    for row in file_reader:
        class_bulk_data.append(row)
    
    return class_bulk_data

def LessonTable(request):

    lesson_all = Lesson.objects.all().order_by('start_time')
    
    if request.method == 'POST':
        #Search Function

        search_value = request.POST.get("search")
        if search_value is not None:
            lesson_all = Lesson.objects.filter(class_name__icontains=search_value)
        
        #for Bulk upload
        form = UploadFileForm(request.POST, request.FILES)
        
        if form.is_valid():
            
            class_bulk_data  = handle_uploaded_file(request.FILES['file'].file, request)
          
            count_Save = 0
            for idx, row in enumerate(class_bulk_data):
                if idx > 0:
                    get_Level = Lesson_level.objects.get(level_name=class_bulk_data[idx][6])
                    new_Class_Entry = Lesson(class_name = class_bulk_data[idx][0], 
                                       class_description = class_bulk_data[idx][1], 
                                       class_capacity = class_bulk_data[idx][2],
                                       start_time = class_bulk_data[idx][3], 
                                       end_time = class_bulk_data[idx][4],
                                       room_location = class_bulk_data[idx][5],
                                       level = get_Level
                                       )
                    new_Class_Entry.save()
                    print (get_Level)
                    count_Save+=1
        print("You Saved:" + str(count_Save))
    else:
        form = UploadFileForm()
      
    context = {'lesson_all': lesson_all,
               'form': form, 
               }
               
    return render(request, 'oneplace/lessontable.html', context)

#does not update the count
class StudentView(generic.ListView):
    template_name = 'oneplace/student.html'
    context_object_name ='student_Info'
    
    studentCount = Student.objects.all().count()

    
    def get_queryset(self):
        return Student.objects.all()

    def get_context_data(self, **kwargs):
        context = super(StudentView, self).get_context_data(**kwargs)
        context.update({'studentCount': self.studentCount})
        return context

def StudentDisplayAll (request):
    student_Info = Student.objects.all().order_by('-student_picture')
    studentCount = Student.objects.all().count()
    context = {'student_Info': student_Info, 
               'studentCount': studentCount}
               
    return render(request, 'oneplace/student.html' , context)


class LessonCreate(CreateView):
	model = Lesson
	fields = ['class_name','class_description','class_capacity', 'start_time','end_time', 'level', 'room_location']


class LessonUpdate(UpdateView):
	model = Lesson
	fields = ['class_name','class_description','class_capacity', 'start_time','end_time', 'room_location', 'level']


class StudentCreate(CreateView):
	model = Student
	fields = ['first_name', 'last_name', 'address', 'state', 'city', 'zipcode', 'cell_phone', 'student_picture']


class StudentUpdate(UpdateView):
	model = Student
	fields = ['first_name', 'last_name', 'address', 'state', 'city', 'zipcode', 'cell_phone', 'student_picture']


class StudentDelete(DeleteView):
	model = Student
	fields = ['first_name', 'last_name', 'address', 'state', 'city', 'zipcode', 'cell_phone', 'student_picture']	
	success_url = reverse_lazy('oneplace:student')

#count does not update corrects so the view below is not in use
class InstructorView(generic.ListView):
    template_name = 'oneplace/instructor.html'
    context_object_name ='instructor_Info'
    
    instructorCount = Instructor.objects.all().count()

    
    def get_queryset(self):
        return Instructor.objects.all()

    def get_context_data(self, **kwargs):
        context = super(InstructorView, self).get_context_data(**kwargs)
        context.update({'instructorCount': self.instructorCount})
        return context
    
def InstructorDisplayAll (request):
    instructor_Info = Instructor.objects.all().order_by('-instructor_picture')
    instructorCount = Instructor.objects.all().count()
    context = {'instructor_Info': instructor_Info, 
               'instructorCount': instructorCount}
               
    return render(request, 'oneplace/instructor.html' , context)
        

class InstructorCreate(CreateView):
	model = Instructor
	fields = ['first_name', 'last_name', 'address','state', 'city', 'zipcode', 'cell_phone', 'rate', 'instructor_picture']


class InstructorUpdate(UpdateView):
	model = Instructor
	fields = ['first_name', 'last_name', 'address', 'state', 'city', 'zipcode', 'cell_phone', 'rate', 'instructor_picture']


class InstructorDelete(DeleteView):
	model = Instructor
	fields = ['first_name', 'last_name', 'address', 'state', 'city', 'zipcode', 'cell_phone','rate', 'instructor_picture']	
	success_url = reverse_lazy('oneplace:instructor')


class StudentEnrollCreate(CreateView):
	model = Student_in_lesson
	fields = ['lesson','student']

#def StudentEnrollDash(request, class_id)

    #return render(request, 'oneplace/class_enrollment.html', context)



class InstructorAssignCreate(CreateView):
	model = Instructor_in_lesson
	fields = [ 'lesson', 'instructor']


class LessonDelete(DeleteView):    
    model = Lesson
    success_url = reverse_lazy('oneplace:lesson')

class LessonDeleteList(DeleteView):    
    model = Lesson
    success_url = reverse_lazy('oneplace:lesson_table')

def ClassEnrollment(request, pk): 
    lesson = Lesson.objects.get(pk=pk)
    student_in_lesson = lesson.student_members.all()
    instructor_assign_lesson = lesson.instructor_members.all()
    student_Count = lesson.student_members.all().count()
    context = {'lesson': lesson, 
               'student_Info': student_in_lesson, 
               'instructor_Info': instructor_assign_lesson,
               'student_Count': student_Count } 
    return render(request, 'oneplace/class_enrollment.html', context)


def StudentRemove(request, studentpk, lessonpk):
	student_delete=Student_in_lesson.objects.get(student=studentpk, lesson=lessonpk)
	student_delete.delete()
	return ClassEnrollment(request, lessonpk)

def InstructorRemove(request, instructorpk, lessonpk):
    instructor_delete=Instructor_in_lesson.objects.get(instructor=instructorpk, lesson=lessonpk)
    instructor_delete.delete()
    return ClassEnrollment(request, lessonpk)

class UserFormView(View):
    form_class = UserForm
    template_name = 'oneplace/registration_form.html'

    #display blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form':form})

#process form data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            #cleaned (normalized) data

oneplace/templates/oneplace/Student_in_lesson_form.html
{% extends 'oneplace/base.html' %}
{% block title %}Assign a Student to a Class{% endblock %}

{% block body %}
<div class="container-fluid">
	<div class = "row">
		<div class="col-sm-12 col-md-6">
			<div class="card">
	  			<div class="card-header"> 
	  				Add a Student to a Class
	  			</div>
	  			<div class="card-block">
	    			<h4 class="card-title">Please Complete Form</h4>
	    			<p class="card-text">This will associate a student to a class in the Database</p>
	    			<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
	    		    {% csrf_token %}
	    		    {% include 'oneplace/template_form.html' %}
	    		    <div class="form-group">
	    		    	<div class="col-sm-offset-2 col-sm-10 col-md-9">
	    		    		<button type="submit" class="btn btn-success">Submit</button>
	    		    	</div>	
	    		    </div>
	    		    </form> 	
	    		   </div>
			</div>
		</div>
	</div>
</div>

{% endblock %}

oneplace/templates/oneplace/base.html
<!DOCTYPE html>
<html>
<head>
<title>{% block title %}Welcome to OnePlace{% endblock %}</title>
{% load staticfiles %}

<!-- Datepicker CSS -->
<link href="{% static 'oneplace/datepicker2.3.7/jquery.datetimepicker.css' %}" rel="stylesheet">

<!-- Bootstrap core CSS -->
<link href="{% static 'oneplace/css/bootstrap.min.css' %}" rel="stylesheet">
<!-- Local Style sheet-->
<link rel="stylesheet" type="text/css" href="{% static 'oneplace/style.css' %}" />
<!--Google Fonts-->
<link rel="stylesheet" type="text/css"
      href="https://fonts.googleapis.com/css?family=Satify">
</head>
<body>
<!-- Jquery to be used by everything-->
<script src="{% static 'oneplace/js/jquery-3.1.1.slim.min.js' %}"></script>


  <nav class="navbar fixed-top navbar-toggleable-md navbar-inverse bg-inverse mb-4">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="{% url  'oneplace:index' %}">OnePlace</a>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url  'oneplace:index' %}">Home<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="{% url  'oneplace:lesson' %}" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true">Classes</a>
             <div class="dropdown-menu">
              <a class="dropdown-item" href="{% url  'oneplace:lesson' %}">All Classes</a>
              <a class="dropdown-item" href="{% url  'oneplace:calendar' %}">Calendar</a>
            </div>
          </li>
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="{% url  'oneplace:student' %}" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"> Students</a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="{% url  'oneplace:student' %}">Students</a>
              <a class="dropdown-item" href="{% url  'oneplace:student_enroll' %}">Enroll a Student</a>
            </div>
          </li>
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="{% url  'oneplace:instructor' %}" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"> Instructors</a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="{% url  'oneplace:instructor' %}">Instructors</a>
              <a class="dropdown-item" href="{% url  'oneplace:instructor_assign' %}">Enroll a Instructor</a>
            </div>
          </li> 
        </ul>
        <ul class="nav navbar-nav navbar-right">
         <li class="nav-item">
            <form class="form-inline mt-2 mt-md-0"  method="post">
            {% csrf_token %}
              <input class="form-control mr-sm-2" name="search" type="text" placeholder="Search">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
          </li>
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="#">Welcome {{ request.user.username }}</a>
           </li>
           <li class="nav-item">
            <a class="nav-link" href="{% url  'oneplace:log_out' %}">Log Out</a>
           </li>
          {% else %}
          <li class="nav-item">  
            <a class="nav-link" href="{% url  'oneplace:register' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url  'oneplace:login' %}">Login</a>
          </li>
          {% endif %}   
        </ul> 
      </div>
  </nav>
{% block body %}
{% endblock %}
<footer class="blog-footer">
      <p class = "lead">For more information Contact qtech411@gmail.com <br>
      <a class="nav-link" href="{% url  'oneplace:rest' %}">API Information</a>
      <p>
        <a href="#">Back to top</a>
      </p>
</footer>

<!-- For highcharts exporting function -->
<script src="{% static 'oneplace/highchart5.0.7/exporting.js' %}"></script>

<!--prereqs-->
<!-- Bootstrap Javascript CDN -->
 
 <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
 <script src="{% static 'oneplace/js/bootstrap.min.js' %}"></script>
</body>
</html>

oneplace/templates/oneplace/charts_capacity.html
{% extends 'oneplace/base.html' %}
{% block title %}Welcome to OnePlace{% endblock %}
{% block body %}
 
   
<div class = "col-md-10 offset-md-1">
    <div class="card">
        <div class="card-header">
            Capacity
        </div>
        <div class="card-block">
            <div id="capacity" style="width:100%; height:400px;"></div>
            <a href="{% url 'oneplace:chart' %}" class="btn btn-primary">Full View</a>
          </div>
        </div>
</div>
   

{% load staticfiles %}


<script src="{% static 'oneplace/highchart5.0.7/highcharts.js' %}"></script>
<script>
Highcharts.chart('capacity', {
    chart: {
        type: 'column'
    },
    title: {
        text: 'Capacity Remaining For Each Class'
    },
    xAxis: {
        categories: [
            {% for lessonName in lessonName %}
                '{{ lessonName }}',
            {% endfor %}
        ]
    },
    yAxis: [{
        min: 0,
        title: {
            text: 'Total Capacity to Enrolled Students'
        }
    }, {
        title: {
            text: ''
        },
        opposite: true
    }],
    legend: {
        shadow: false
    },
    tooltip: {
        shared: true
    },
    plotOptions: {
        column: {
            grouping: false,
            shadow: false,
            borderWidth: 0
        }
    },
    series: [ {
        name: 'Class Capacity',
        color: 'rgba(248,161,63,1)',
        data: [{% for lessonMaxEnrollment in lessonMaxEnrollment %}
                  {{ lessonMaxEnrollment }},
               {% endfor %}],
        pointPadding: 0.3,
        pointPlacement: 0.2,
        yAxis: 1
    }, {
        name: '# of students Enrolled',
        color: 'rgba(186,60,61,.9)',
        data: [{% for lessonStudentCount  in lessonStudentCount %}
            {{ lessonStudentCount }},
            {% endfor %}],
        pointPadding: 0.4,
        pointPlacement: 0.2,
        yAxis: 1
    }]
});

</script>
   
{% endblock %}

oneplace/templates/oneplace/index.html
{% extends 'oneplace/base.html' %}
{% block title %}Welcome to OnePlace{% endblock %}
{% block body %}
<div class="jumbotron">
    <div class="container tsquare">
        <h1>OnePlace</h1>
        <p class="lead">Welcome to OnePlace. The site for Brooklyn Conservatory of Music to track events, classes, students, and <br> generating reports. </p>   
    </div>
</div>
<div class="container">
    <div class="card-deck">
        <div class = "col-md-4">
            <div class="card carddown">
                <img class="card-img-top img-fluid" src="../../static/oneplace/images/class.jpg" alt="Card image cap">
                  <div class="card-block">
                    <h4 class="card-title">Classes</h4>
                    <p class="card-text">View List of available Classes</p>
                    <a href="{% url 'oneplace:lesson_table' %}" class="btn btn-primary">Class List</a>
                  </div>
            </div>
        </div>
        <div class = "col-md-4">
            <div class="card carddown">
                <img class="card-img-top img-fluid" src="../../static/oneplace/images/report.jpg" alt="Card image cap">
                  <div class="card-block">
                    <h4 class="card-title">Reports</h4>
                    <p class="card-text">Check out the reporting features </p>
                    <a href="{% url 'oneplace:chart' %}" class="btn btn-primary">Available Reports</a>
                  </div>
            </div>
        </div>
        <div class ="col-md-4">
            <div class="card carddown">
                <img class="card-img-top img-fluid" src="../../static/oneplace/images/clock.jpg" alt="Card image cap">
                  <div class="card-block">
                    <h4 class="card-title">Calendar</h4>
                    <p class="card-text">View all scheduled classes</p>
                    <a href="{% url 'oneplace:calendar' %}" class="btn btn-primary">View Calendar</a>
                  </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

oneplace/templates/oneplace/instructor_form.html
{% extends 'oneplace/base.html' %}
{% block title %}Add Instructor{% endblock %}

{% block body %}
<div class="container-fluid">
	<div class = "row">
		<div class="col-sm-12 col-md-6">
			<div class="card">
	  			<div class="card-header"> 
	  				Add a Instructor
	  			</div>
	  			<div class="card-block">
	    			<h4 class="card-title">Please Complete Form</h4>
	    			<p class="card-text">This will add a new Instructor to the Database</p>
	    			<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
	    		    {% csrf_token %}
	    		    {% include 'oneplace/template_form.html' %}
	    		    <div class="form-group">
	    		    	<div class="col-sm-offset-2 col-sm-10 col-md-9">
	    		    		<button type="submit" class="btn btn-success">Submit</button>
	    		    	</div>	
	    		    </div>
	    		    </form> 	
	    		   </div>
			</div>
		</div>
	</div>
</div>

{% endblock %}

oneplace/templates/oneplace/student.html
{% extends 'oneplace/base.html' %}
{% block title %}All Students{% endblock %}
{% block body %}
<div class = "container-fluid">


<div class="row">
  <div class = "col-md-12">
    <div class="card cardmain">
     <div class="card-header">
              <h5 class ="col-lg-10">Students</h5>
        </div>
          <div class="card-block">
            <h4>Total Students: {{ studentCount }}</h4>
      <!-- Start Table -->
      <div class = "offset-md-1 col-md-10" >
      <a href="{% url 'oneplace:student_add' %}" class="btn btn-primary btn active studentbtnadd">Add Student</a>
            <table class = "table table-responsive table-striped " id ="tablesort">
              <thead>
                <tr>
                  <th onclick="sortTable(0)" class="nicehover">Profile Pic</th>
                  <th onclick="sortTable(1)" class="nicehover">Student First Name</th>
                  <th onclick="sortTable(2)" class="nicehover">Student Last Name</th>
                  <th onclick="sortTable(3)" class="nicehover">Address</th>
                  <th onclick="sortTable(4)" class="nicehover">Zip Code</th>
                  <th onclick="sortTable(5)" class="nicehover">State</th>
                  <th onclick="sortTable(6)" class="nicehover">City</th>
                  <th></th>
                  <th></th>
                </tr>
              <thead>
            <tbody>

               {% for sdtvalue in student_Info %}
              <tr>
                <td scope="row"><img src="{{ sdtvalue.student_picture.url }}" class="img-responsive" width="75" height="75"></td>
                <td>{{ sdtvalue.first_name }}</td>
                <td>{{ sdtvalue.last_name }}</td>
                <td>{{ sdtvalue.address }}</td>
                <td>{{ sdtvalue.zip_code }}</td>
                <td>{{ sdtvalue.state }}</td>
                <td>{{ sdtvalue.city }}</td>
                <td> 
                    <form action="{% url 'oneplace:student_update' sdtvalue.id %}">
                    {% csrf_token %}
                      <button type = "submit" class="btn btn-outline-info btn-sm">Update</button>
                    </form>
                  </td>
                  <td> 
                    <form action="{% url 'oneplace:student_delete' sdtvalue.id %}" method="post">
                    {% csrf_token %}
                      <button type = "submit" class="btn btn-outline-danger btn-sm">Delete</button>  
                    </form>
                  </td>
              </tr>
            {% endfor %}

            </tbody>
            </table>
        </div>
            <!-- END Table -->

 
     </div>
    </div>
  </div>
</div>

</div>
{% load staticfiles %}
<script src="/static/oneplace/js/customsorttable.js"></script>
{% endblock %}

oneplace/templates/oneplace/template_student_list.html
<table class = "table table-responsive table-striped">
  <thead>
    <tr>
      <th>Profile Pic</th>
      <th>Student First Name</th>
      <th>Student Last Name</th>
      <th>Address</th>
      <th>Zip Code</th>
      <th>State</th>
      <th>City</th>
      <th></th>
      <th></th>
    </tr>
  <thead>
<tbody>
<tr>
   {% for sdtvalue in student_Info %}
  <tr>
    <td scope="row"><img src="{{ sdtvalue.student_picture.url }}" class="img-responsive" width="100" height="100"></td>
    <td>{{ sdtvalue.first_name }}</td>
    <td>{{ sdtvalue.last_name }}</td>
    <td>{{ sdtvalue.address }}</td>
    <td>{{ sdtvalue.zip_code }}</td>
    <td>{{ sdtvalue.state }}</td>
    <td>{{ sdtvalue.city }}</td>
    <td> 
        <form action="{% url 'oneplace:student_update' sdtvalue.id %}">
        {% csrf_token %}
          <button type = "submit" class="btn btn-outline-info btn-sm">Update</button>
        </form>
      </td>
      <td> 
        <form action="{% url 'oneplace:student_delete' sdtvalue.id %}" method="post">
        {% csrf_token %}
          <button type = "submit" class="btn btn-outline-danger btn-sm">Delete</button>  
        </form>
      </td>
  </tr>
{% endfor %}
</tbody>
</table>