myproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^oneplace/', include('oneplace.urls')),
    url(r'^nonprofit/', include('nonprofit.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nonprofit/urls.py
from django.conf.urls import url

from . import views

app_name = 'nonprofit'

urlpatterns = [
    url(r'^home/$', views.home, name='home'),
    url(r'^class/$', views.LessonView.as_view(), name='lesson'),
    url(r'^class/(?P<class_field>[C][0-9]+)/$', views.student, name='student'),
    url(r'^instructor/form/$', views.instructor_form, name='instructor_form'),
    url(r'^instructor/add/$', views.instructor_add, name='instructor_add'),
    url(r'^class/add/$', views.LessonCreate.as_view(), name='lesson_add'),
    url(r'^class/update/(?P<pk>[C][0-9]+)/$', views.LessonUpdate.as_view(), name='lesson_update'),
    url(r'^class/delete/(?P<pk>[C][0-9]+)/$', views.LessonDelete.as_view(), name='lesson_delete')
    
]

'''url(r'^$', views.index, name='index'),
    url(r'^(?P<class_field>[C][0-9]+)/$', views.student, name='student'),
    url(r'^(?P<pk>[C][0-9]+)/$', views.StudentView.as_view(), name='student'),
    '''

oneplace/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from oneplace import views
from . import views

app_name = 'oneplace'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^class/$', views.LessonView.as_view(), name='lesson'),
    url(r'^class/table/$', views.LessonTable, name='lesson_table'),
    #url(r'^class/table/$', views.LessonTableView.as_view(), name='lesson_table'),
    url(r'^class/add/$', views.LessonCreate.as_view(), name='lesson_add'),
    url(r'^class/update/(?P<pk>[0-9]+)/$', views.LessonUpdate.as_view(), name='lesson_update'),
    url(r'^class/delete/(?P<pk>[0-9]+)/$', views.LessonDelete.as_view(), name='lesson_delete'),
    url(r'^class/delete/(?P<pk>[0-9]+)/list/$', views.LessonDeleteList.as_view(), name='lesson_delete_list'),
    url(r'^class/calendar/$', views.calendar, name='calendar'),
    url(r'^student/$', views.StudentDisplayAll, name='student'),
    url(r'^student/add/$', views.StudentCreate.as_view(), name='student_add'),
    url(r'^student/update/(?P<pk>[0-9]+)/$', views.StudentUpdate.as_view(), name='student_update'),
    url(r'^student/delete/(?P<pk>[0-9]+)/$', views.StudentDelete.as_view(), name='student_delete'),
    url(r'^student/remove/(?P<studentpk>[0-9]+)/(?P<lessonpk>[0-9]+)$', views.StudentRemove, name='student_remove'),
    url(r'^instructor/$', views.InstructorDisplayAll, name='instructor'),
    url(r'^instructor/add/$', views.InstructorCreate.as_view(), name='instructor_add'),
    url(r'^instructor/delete/(?P<pk>[0-9]+)/$', views.InstructorDelete.as_view(), name='instructor_delete'),
    url(r'^instructor/update/(?P<pk>[0-9]+)/$', views.InstructorUpdate.as_view(), name='instructor_update'),
    url(r'^instructor/remove/(?P<instructorpk>[0-9]+)/(?P<lessonpk>[0-9]+)$', views.InstructorRemove, name='instructor_remove'),
    url(r'^student/enroll/$', views.StudentEnrollCreate.as_view(), name='student_enroll'),
    url(r'^instructor/assign/$', views.InstructorAssignCreate.as_view(), name='instructor_assign'),
    url(r'^class/enrollment/(?P<pk>[0-9]+)/$', views.ClassEnrollment, name='class_enrollment'),
    url(r'^register/$', views.UserFormView.as_view(), name='register'),
    url(r'^login/$', views.LoginFormView.as_view(), name='login'),
    url(r'^logout/$', views.logoutView, name='log_out'),
    url(r'^rest/api$', views.StudentList.as_view(), name='rest'),
    url(r'^chart/$', views.chart, name='chart'),
    url(r'^chart/charttotalstudent$', views.chart_total_student, name='chart_total_student'),
    url(r'^chart/chartclasspermonth$', views.chart_class_per_month, name='chart_class_per_month'),
    url(r'^chart/chartcapacity$', views.chart_capacity, name='chart_capacity'),
    url(r'^chart/chart_level$', views.chart_level, name='chart_level'),
    url(r'^test$', views.test, name='test'),
    
    ]

urlpatterns = format_suffix_patterns(urlpatterns)

#maybe use later
#url(r'^student/$', views.StudentView.as_view(), name='student'),
#url(r'^instructor/$', views.InstructorView.as_view(), name='instructor'),

nonprofit/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals
from django.db import models
from django.core.urlresolvers import reverse


class BridgeClassEnroll(models.Model):
    id = models.CharField(max_length=100, primary_key=True)
    class_field = models.ForeignKey('Class', models.DO_NOTHING, db_column='class_id')  # Field renamed because it was a Python reserved word.
    student = models.ForeignKey('Student', models.DO_NOTHING)
    enrollment_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
         return str(self.class_field) + ' - ' + str(self.student)  + ' - ' + str(self.enrollment_date)

    class Meta:
        db_table = 'django_bridge_class_enroll'
        unique_together = (('student', 'class_field'),)


class BridgeInstructorEnroll(models.Model):
    id = models.CharField(max_length=100, primary_key=True)
    class_field = models.ForeignKey('Class', models.DO_NOTHING, db_column='class_id')  # Field renamed because it was a Python reserved word.
    rocket = models.ForeignKey('Instructor', models.DO_NOTHING)
    assignment_date = models.DateTimeField(blank=True, null=True)
    
    def __str__(self):
         return str(self.class_field) + ' - ' + str(self.rocket)  + ' - ' + str(self.assignment_date)

    class Meta:
        db_table = 'django_bridge_instructor_enroll'
        unique_together = (('rocket', 'class_field'),)


class Class(models.Model):
    class_id = models.CharField(primary_key=True, max_length=20)
    class_name = models.CharField(max_length=50)
    class_description = models.CharField(max_length=500)
    class_capacity = models.IntegerField(blank=True, null=True)
    start_time = models.DateTimeField(blank=True, null=True)
    end_time = models.DateTimeField(blank=True, null=True)
    level = models.ForeignKey('ClassLevel', models.DO_NOTHING, blank=True, null=True)
    def __str__(self):
         return self.class_id + ' - ' + self.class_name
    

    def get_absolute_url(self):
        return reverse('nonprofit:lesson')

    class Meta:
        db_table = 'django_class'


class ClassLevel(models.Model):
    level_id = models.CharField(primary_key=True, max_length=20)
    level_name = models.CharField(max_length=50)
    level_description = models.CharField(max_length=250, blank=True, null=True)
    def __str__(self):
         return self.level_id + ' - ' + self.level_name

    class Meta:
        db_table = 'django_class_level'

class Instructor(models.Model):
    rocket_id = models.CharField(primary_key=True, max_length=20)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    address = models.CharField(max_length=50, blank=True, null=True)
    zip_code = models.CharField(max_length=10, blank=True, null=True)
    state = models.CharField(max_length=20, blank=True, null=True)
    city = models.CharField(max_length=50, blank=True, null=True)
    cell_phone = models.CharField(max_length=20)
	
    def __str__(self):
         return self.rocket_id + ' - ' + self.first_name + ' ' + self.last_name
    
    def get_absolute_url(self):
        return reverse('nonprofit/lesson')

    class Meta:
        db_table = 'django_instructor'


class Student(models.Model):
    student_id = models.CharField(primary_key=True, max_length=20)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    address = models.CharField(max_length=50, blank=True, null=True)
    zip_code = models.CharField(max_length=10, blank=True, null=True)
    state = models.CharField(max_length=20, blank=True, null=True)
    city = models.CharField(max_length=50, blank=True, null=True)
    cell_phone = models.CharField(max_length=20)
    student_picture = models.FileField(null=True)
    
    def __str__(self):
         return 'Student ID: ' + self.student_id + ' - ' + str(self.first_name)  + ' ' + str(self.last_name)

    class Meta:
        db_table = 'django_student'

nonprofit/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render, get_object_or_404
from .models import Class, Student, ClassLevel, Instructor, BridgeInstructorEnroll, BridgeClassEnroll
from django.core.urlresolvers import reverse_lazy

def home(request):
	return render(request, 'nonprofit/index.html')

class LessonView(generic.ListView):
    template_name = 'nonprofit/class_detail.html'
    context_object_name ='all_Class'
    def get_queryset(self):
        return Class.objects.all()
        

def student(request, class_field): 
    student_List = BridgeClassEnroll.objects.filter(class_field=class_field)  
    student_Count = BridgeClassEnroll.objects.filter(class_field=class_field).count()
    lesson = Class.objects.get(pk=class_field)
    student_Info = []
    
    lessonExists = get_object_or_404(Class, pk = class_field)


    for student_pk in student_List.values():
        student_row=Student.objects.get(pk = student_pk['student_id'])
        student_Info.append(student_row)
       
    context = {'all_Student': student_List, 
               'lesson': lesson, 
               'student_Info': student_Info,
               'student_Count': student_Count } 
    return render(request, 'nonprofit/student.html', context)


def instructor_form(request):
    all_Class = Class.objects.all() 
    context = {'all_Class' : all_Class,
               }
    '''print(request.POST['last_n'])'''
    '''print(request.POST['phone_Number'])'''

    return render(request, 'nonprofit/instructor.html', context)

def instructor_add(request):
    all_Class = Class.objects.all() 
    context = {'all_Class' : all_Class,
               }
    new_instructor = Instructor()
    new_instructor.rocket_id = request.POST['rocket_id']
    new_instructor.first_name = request.POST['first_n']
    new_instructor.last_name = request.POST['last_n']
    new_instructor.address = request.POST['address']
    new_instructor.zip_code = request.POST['zip_code']
    new_instructor.state = request.POST['state']
    new_instructor.cell_phone = request.POST['phone_number']
    new_instructor.save()
    
    return render(request, 'nonprofit/instructor.html', context)

class LessonCreate(CreateView):
	model = Class
	fields = ['class_id','class_name','class_description','class_capacity', 'start_time','end_time']


class LessonUpdate(UpdateView):
    model = Class
    fields = ['class_id','class_name','class_description','class_capacity', 'start_time','end_time']

class LessonDelete(DeleteView):
    
    
    model = Class
    success_url = reverse_lazy('nonprofit:lesson')

    def get_object(self):
        student_List = BridgeClassEnroll.objects.filter(class_field=self.class_id)
        return self.model.objects.get(class_id=self.request.POST.get('class_id'))

nonprofit/templates/nonprofit/base.html
<!DOCTYPE html>
<html>
<head>
<title>{% block title %}Your Scheduling Portal{% endblock %}</title>

    
    

{% load staticfiles %}
<!-- Bootstrap core CSS -->
<link href="{% static 'nonprofit/css/bootstrap.min.css' %}" rel="stylesheet">
<!-- Local Style sheet-->
<link rel="stylesheet" type="text/css" href="{% static 'nonprofit/style.css' %}" />
<!--Google Fonts-->
<link rel="stylesheet" type="text/css"
      href="https://fonts.googleapis.com/css?family=Satify">



</head>
<body>

<nav class="navbar fixed-top navbar-toggleable-md navbar-inverse bg-inverse mb-4">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="{% url  'nonprofit:home' %}">OnePlace</a>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url  'nonprofit:home' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url  'nonprofit:lesson' %}">Classes</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url  'nonprofit:instructor_form' %}">Intructors</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Students</a>
          </li>
        </ul>
        <form class="form-inline mt-2 mt-md-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

{% block body %}
{% endblock %}
<footer class="blog-footer">
      <p class = "lead">For more information Contact qtech411@gmail.com
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>


<!--prereqs-->
<!-- Bootstrap Javascript JQuery CDN -->
 <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="{% static 'nonprofit/js/bootstrap.min.js' %}"></script>
</body>
</html>

nonprofit/templates/nonprofit/base2.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
   
    
    <title>Home</title>

    <!-- Bootstrap core CSS -->
    <link href="../../static/nonprofit/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="../../static/nonprofit/style.css" rel="stylesheet">
  </head>
<body>

<nav class="navbar fixed-top navbar-toggleable-md navbar-inverse bg-inverse mb-4">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="#">One Place</a>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Classes</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Intructors</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Students</a>
          </li>
        </ul>
        <form class="form-inline mt-2 mt-md-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

<div class="jumbotron">
    <div class="container tsquare">
        <h1>OnePlace</h1>
        <p class="lead">Welcome to onePlace. The site where you can set up a group or company and track events, classes, generate reports, and take donations</p>
        
    </div>
</div>

<div class="container">
    <div class="card-deck">
        <div class = "col-md-4">
            <div class="card">
                <img class="card-img-top img-fluid" src="../../static/nonprofit/images/class.jpg" alt="Card image cap">
                  <div class="card-block">
                    <h4 class="card-title">Classes</h4>
                    <p class="card-text">View List of available Classes</p>
                    <a href="#" class="btn btn-primary">Class List</a>
                  </div>
            </div>
        </div>
        <div class = "col-md-4">
            <div class="card">
                <img class="card-img-top img-fluid" src="../../static/nonprofit/images/report.jpg" alt="Card image cap">
                
                  <div class="card-block">
                    <h4 class="card-title">Reports</h4>
                    <p class="card-text">Check out the reporting features </p>
                    <a href="#" class="btn btn-primary">Available Reports</a>
                  </div>
            </div>
        </div>
        <div class ="col-md-4">
            <div class="card">
                <img class="card-img-top img-fluid h-50 d-inline-block" src="../../static/nonprofit/images/jar.jpg" alt="Card image cap">
                  <div class="card-block">
                    <h4 class="card-title">Donations</h4>
                    <p class="card-text">Donate to a nonprofit today</p>
                    <a href="#" class="btn btn-primary">Donate Today</a>
                  </div>
            </div>
        </div>
    </div>
</div>


 <footer class="blog-footer">
      <p class = "lead">For more information Contact qtech411@gmail.com
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>

<!--prereqs-->
 <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="../../static/nonprofit/js/bootstrap.min.js"></script>

  </body>
</html>

nonprofit/templates/nonprofit/class.html
 
{% extends 'nonprofit/base.html' %}
{% block body %}

<div class = "container-fluid">
  <div class="card-deck">
{% for classvalue in all_Class %}
    <div class = "col-lg-4 cont_pad">
      <div class="card">
        <div class="card-header">
          <h4>{{ classvalue.class_name }}</h4>
        </div>
        <div class="card-block">
          <p class="lead">{{ classvalue.class_description }}</p>
          <p> {{ classvalue.start_time }}<br> {{ classvalue.end_time }}</p>
          <p> Maximum Capacity: {{ classvalue.class_capacity }}</p>  
        </div>
      <a href="#" class="btn btn-primary">View Enrollment</a>
      </div>
    </div>
{% endfor %}
</div>
</div>
{% endblock %}

nonprofit/templates/nonprofit/class_detail.html
 
{% extends 'nonprofit/base.html' %}
{% block body %}
<div class = "container-fluid">
<div class = "col-lg-4 ">
<a href="{% url 'nonprofit:lesson_add' %}" class="btn btn-primary btn-lg active classbtnadd">Add Class</a>
</div>
  <div class="card-deck">
{% for classvalue in all_Class %}
    <div class = "col-lg-4 cont_pad">
      <div class="card cardspec">
        <div class="card-header">
          <h4>{{ classvalue.class_name }}
            <form action="{% url 'nonprofit:lesson_delete' classvalue.class_id %}" method="post">
              {% csrf_token %}
                <button type = "submit" class="btn btn-outline-danger btn-sm classbtndel">Delete</button>  
             </form>  
             <form action="{% url 'nonprofit:lesson_update' classvalue.class_id %}">
              {% csrf_token %}
             <button type = "submit" class="btn btn-outline-info btn-sm classbtnupd">Update</button>
             </form>   
          </h4>
        </div>
        <div class="card-block">
          <p class="lead">{{ classvalue.class_description }}</p>
          <p> {{ classvalue.start_time }}<br> {{ classvalue.end_time }}</p>
          <p> Maximum Capacity: {{ classvalue.class_capacity }}</p>  
        </div>
      <a href="{% url 'nonprofit:student' classvalue.class_id %}" class="btn btn-primary">View Enrollment</a>
      </div>
    </div>
{% endfor %}
</div>
</div>
{% endblock %}

nonprofit/templates/nonprofit/class_form.html
{% extends 'nonprofit/base.html' %}
{% block title %}Add Class{% endblock %}

{% block body %}
<div class="container-fluid">
	<div class = "row">
		<div class="col-sm-12 col-md-6">
			<div class="card">
	  			<div class="card-header"> 
	  				Add a Class
	  			</div>
	  			<div class="card-block">
	    			<h4 class="card-title">Please Complete Form</h4>
	    			<p class="card-text">This will add a new Class to the Database</p>
	    			<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
	    		    {% csrf_token %}
	    		    {% include 'nonprofit/form_template.html' %}
	    		    <div class="form-group">
	    		    	<div class="col-sm-offset-2 col-sm-10 col-md-9">
	    		    		<button type="submit" class="btn btn-success">Submit</button>
	    		    	</div>	
	    		    </div>
	    		    </form> 	
	    		   </div>
			</div>
		</div>
	</div>
</div>

{% endblock %}

nonprofit/templates/nonprofit/datepicker.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>jQuery UI Datepicker - Default functionality</title>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
  $( function() {
    $( "#datepicker" ).datepicker();
  } );
  </script>
</head>
<body>
 
<p>Date: <input type="text" id="datepicker"></p>
 
 
</body>
</html>

nonprofit/templates/nonprofit/instructor.html
{% extends 'nonprofit/base.html' %}

{% block title %}
Instructor Form
{% endblock %}

{% block body %}
<h3>Add Insructor</h3>
 <form action="{% url 'nonprofit:instructor_add' %}" method = "post">
 {% csrf_token %}
  <table>
  <tr>
      <td align="right">Instructor ID:</td>
      <td align="left"><input type="text" id="rocket_id" name = "rocket_id" value=""/></td>
    </tr>
    <tr>
      <td align="right">First Name:</td>
      <td align="left"><input type="text" id="first_n" name = "first_n" value=""/></td>
    </tr>
    <tr>
      <td align="right">Last Name:</td>
      <td align="left"><input type="text" id="last_n" name = "last_n" value=""/></td>
    </tr>
    <tr>
      <td align="right">Address:</td>
      <td align="left"><input type="text" id="address" name = "address" value=""/></td>
    </tr>
    <tr>
      <td align="right">Zip Code:</td>
      <td align="left"><input type="text" id="zip_code" name = "zip_code" value=""/></td>
    </tr>
    <tr>
      <td align="right">State:</td>
      <td align="left"><input type="text" id="state" name = "state" value=""/></td>
    </tr>
    <tr>
      <td align="right">City:</td>
      <td align="left"><input type="text" id="city" name = "city" value=""/></td>
    </tr>
    <tr>
      <td align="right">Phone Number:</td>
      <td align="left"><input type="text" id="phone_number" name = "phone_number" value=""/></td>
    </tr>
    <tr>
    <td align="right">Assign to Class:</td>
    <td align="right"> <select>
    						{% for classvalue in all_Class %}
                            <option value={{classvalue.class_name }}>{{ classvalue.class_name }}</option>
                            {% endfor %}
                            </select>
        </td>
    </tr>
    <tr>
      <td align="right"></td>
      <td align="right"><input type="submit" name = "instructors" value="Submit"/></td>
    </tr>
  </table>
</form>
<!--
<div class="form-group row">
  <label for="example-text-input" class="col-1 col-form-label">Text</label>
  <div class="col-3">
    <input class="form-control" type="text" value="Artisanal kale" id="example-text-input">
  </div>
</div>
<div class="form-group row">
  <label for="example-search-input" class="col-2 col-form-label">Search</label>
  <div class="col-3">
    <input class="form-control" type="search" value="How do I shoot web" id="example-search-input">
  </div>
</div>
<div class="form-group row">
  <label for="example-email-input" class="col-2 col-form-label">Email</label>
  <div class="col-3">
    <input class="form-control" type="email" value="bootstrap@example.com" id="example-email-input">
  </div>
</div>
<div class="form-group row">
  <label for="example-url-input" class="col-2 col-form-label">URL</label>
  <div class="col-10">
    <input class="form-control" type="url" value="https://getbootstrap.com" id="example-url-input">
  </div>
</div>
<div class="form-group row">
  <label for="example-tel-input" class="col-2 col-form-label">Telephone</label>
  <div class="col-10">
    <input class="form-control" type="tel" value="1-(555)-555-5555" id="example-tel-input">
  </div>
</div>
<div class="form-group row">
  <label for="example-password-input" class="col-2 col-form-label">Password</label>
  <div class="col-10">
    <input class="form-control" type="password" value="hunter2" id="example-password-input">
  </div>
</div>
<div class="form-group row">
  <label for="example-number-input" class="col-2 col-form-label">Number</label>
  <div class="col-10">
    <input class="form-control" type="number" value="42" id="example-number-input">
  </div>
</div>
<div class="form-group row">
  <label for="example-datetime-local-input" class="col-2 col-form-label">Date and time</label>
  <div class="col-10">
    <input class="form-control" type="datetime-local" value="2011-08-19T13:45:00" id="example-datetime-local-input">
  </div>
</div>
<div class="form-group row">
  <label for="example-date-input" class="col-2 col-form-label">Date</label>
  <div class="col-10">
    <input class="form-control" type="date" value="2011-08-19" id="example-date-input">
  </div>
</div>
<div class="form-group row">
  <label for="example-month-input" class="col-2 col-form-label">Month</label>
  <div class="col-10">
    <input class="form-control" type="month" value="2011-08" id="example-month-input">
  </div>
</div>
<div class="form-group row">
  <label for="example-week-input" class="col-2 col-form-label">Week</label>
  <div class="col-10">
    <input class="form-control" type="week" value="2011-W33" id="example-week-input">
  </div>
</div>
<div class="form-group row">
  <label for="example-time-input" class="col-2 col-form-label">Time</label>
  <div class="col-10">
    <input class="form-control" type="time" value="13:45:00" id="example-time-input">
  </div>
</div>
<div class="form-group row">
  <label for="example-color-input" class="col-2 col-form-label">Color</label>
  <div class="col-10">
    <input class="form-control" type="color" value="#563d7c" id="example-color-input">
  </div>
</div>
-->
{% endblock %}